# Dockerfile pour exécuter l'émulateur RISC-V (Livrable 4)
FROM python:3.9-slim

RUN apt-get update && apt-get install -y python3-pip

COPY . /app
WORKDIR /app

RUN pip install -r requirements.txt

ARG BINARY_FILE

RUN echo "4" > livrable.prop

CMD ["python", "main.py", "${BINARY_FILE}", "--livrable", "4", "--step"]